### ISSUE TITLE
Ability for the tenant owner to list namespaces in the tenant

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#18]
# Describe the feature
Ability for the tenant owner to list namespaces in the tenant. Currently, the tenant owner can create and delete namespaces in his tenants but listing them is prevented by RBAC. And this is correct, according to RBAC rules, otherwise the tenant owner can list all the namespaces in the cluster (namespace is a cluster-wide resource). 

Generally speaking, the ability to list only the owned namespaces has been long discussed in the community, see kubernetes/kubernetes#48537, kubernetes/kubernetes#58262, and kubernetes/kubernetes#61958 and the objections described there still hold.

As reported in this [comment](https://github.com/kubernetes/kubernetes/issues/61958#issuecomment-377613898) there are no ACL-filtered APIs in core kubernetes. Filtering resources through ACL breaks resourceVersion semantics that allow watch to function properly.

# What would the new user story look like?
As tenant owner, I would be able to create, list, and delete namespaces in my tenant.

# Expected behavior
See above

**Comment by bsctl** [comment]
what about to implement this feature as part of a custom cli?

```bash
$ capsulectl list namespaces --tenant=mytenant 

NAME STATUS   AGE   TENANT
usl1 Active   53m   mytenant
usl2 Active   53m   mytenant
usl3 Active   53m   mytenant

**Comment by prometherion** [comment]
Tough feature this one, let's try to evaluate each one.

---

Overcoming a Kubernetes limitation, as you said with the [first](https://github.com/clastix/capsule/issues/18#issue-667283713) comment is quite hard: the unique to bypass it should be the mirroring of Namespace resources to a _Tenant Namespace_ resources, cloned into each Namespace managed by the Tenant.

Although this could sound the more suitable and Kubernetes-alike since just `kubectl` is needed, makes the management and reconciliation too much complicated: what I like of Capsule is its native integration with Kubernetes without the need of several CRDs (tl;dr; KISS principle).

---

Implementing a CLI, as you suggested, would be much better but I see an important drawback: the CLI should need access to the Capsule Pod running on its namespace (actually, hardcoded to `capsule-system`) making it impossible from a Tenant perspective to interact with it since the role `admin` is granted only to their Namespaces.

Nothing to overcome since we should just allow at _NetworkPolicy_ level the communication between Tenant namespaces and the API Server running on `capsule-system`.

From my perspective, the CLI solution is the cleaner way: we could use the `kubectl port-forward` capabilities (so no need of CA or weird tricks) using the certificate provided by the `kubeconfig` retrieving the _CN_ along with the Indexer already implemented.

https://github.com/clastix/capsule/blob/fef3607ecf3cdd21c2f26cf42491c433e6b8cfde/pkg/indexer/tenant/owner.go#L14-L39

We should need a new repository, at least for the CLI, and checking if we could hack the current code-base in order to reuse the actual code-base: we could take advantage of this and providing also further capabilities, like reporting the whole Tenant ResourceQuota usage rather than using annotations.

Although sound exciting I would keep this feature request as a low priority since we're not yet out of the alpha phase and I'd like first to get feedback and suggestions from the community.

**Comment by bsctl** [comment]
We should have addressed this problem with the [`ns-filter`](https://github.com/clastix/capsule-ns-filter) tool. @prometherion Can we close this issue?

**Comment by prometherion** [comment]
We can close it once opened the said repo :)

**Comment by prometherion** [comment]
Closing, `capsule-ns-filter` was born! ❤️
