### ISSUE TITLE
Add new group as an exception of the capsule-user-group

### ISSUE THREAD

**Issue by stg-0** [clastix/capsule#234]
Hi everyone!

I've found an issue using Capsule in a (IMHO) non-conventional way, that's why I think this is a feature request and not a bug.

I've deployed Capsule on my k8s cluster, and used system:authenticated as the capsule-user-group so no user in Kubernetes remains outside the multi-tenancy, but when I tried to delete a Namespace with a NetworkPolicy created by the Tenant, I got an error code 500.

As far as I can tell, this error was caused by the AdmissionRequest for NetworkPolicy deletion sent by the controller (username: system:serviceaccount:kube-system:namespace-controller) which doesn't have a Name (referenced by the AdmissionRequest.Name), so the Get on the generic function cannot find the Resource.

I've fixed that error getting the Name from the OldObject in the AdmissionRequest, but then I got an error code 403.

Trying to understand this error, I've found out that Capsule's validating webhook allows requests for users outside the capsule-user-group without applying any filtering, but the request from the controller has the system:authenticated group I've configured.

So I came up with this idea for my use case: what if Capsule had an extra parameter to indicate a "system group" so a request with that group is considered "outside of Capsule" ?

That way, I could easily specify for example --system-user-group=system:serviceaccounts:kube-system and keep the --capsule-user-group=system:authenticated.

What do you think?

**Comment by prometherion** [comment]
First of all, thanks for giving Capsule a try! 🤗 

> I've deployed Capsule on my k8s cluster, and used system:authenticated as the capsule-user-group so no user in Kubernetes remains outside the multi-tenancy

I'd say this, although non documented, it's a bad practice: the issue is that RBAC is used by several components in Kubernetes, such as `system:node` used by the Kubelet certificate, etc. Multi-tenancy should be applied just to a small set of users and the `system:authenticated` group is a too much broader audience, bringing side-effects or issuess as the one as you just faced.

> what if Capsule had an extra parameter to indicate a "system group" so a request with that group is considered "outside of Capsule" ?

Using the additional CLI parameter to exclude users from the validation would be bad since it smells like a workaround for a code that is malformed.

Besides this clarification, I think we could refactor a little bit the middleware we're using here:

https://github.com/clastix/capsule/blob/56adfe6a35d2271f1556d794614007aee656dbb5/main.go#L176-L178

Instead of relying on the group belonging, we could perform these tasks:

- checking if the resource (NetworkPolicy for the said case) is managed by Capsule
- if it's not, passthrough
- otherwise, if the request is *not*  made by Capsule or belonging to `system:serviceaccounts:kube-system`, deny the request

If you don't mind, I can take care of this: debugging webhooks locally it's a pain, although we documented how to achieve it! :)

**Comment by prometherion** [comment]
Let's ignore the last checklist because in the end we just need to verify if the request has been generated by a ServiceAccount in the `kube-system` Namespace!

PR on it's way.

**Comment by stg-0** [comment]
When thinking solutions for this issue I discarded checking for a specific group just to make it more configurable for other use cases, but I also didn't like to add a new parameter. You've chosen the latter which I think is a good decision.

Thanks!
