### ISSUE TITLE
Cordon a tenant for maintenance

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#243]
# Describe the feature
Inspired by  the [kube-anchor](https://github.com/JESWINKNINAN/kube-anchor) project, it would be nice to leave the cluster admin to "cordon" a tenant for maintenance during a Production Freeze Window.

### Some possible use cases:

- Avoid accidental resource modification(s) including deletion during a Production Freeze Window
- During Kubernetes upgrade, to prevent any workload updates
- During incidents or outages
- During planned maintenance of a dedicated nodes pool in a BYOD scenario 

# What would the new user story look like?
1. The cluster admin has to schedule a Production Freeze Window for maintenance
2. He informs the tenant owners that their tenants will be frozen for a while. During this window, no CREATE/UPDATE/DELETE operations are permitted in the impacted tenants.
3. The cluster admin places a label to the tenant, eg.
               
```
$ kubectl label tenant oil capsule.clastix.io/cordon=enabled
tenant oil labeled
```

# Expected behavior
When a tenant is cordoned by cluster admin, a Capsule Admission WebHook denies all CREATE/UPDATE/DELETE user's requests in the cordoned tenant's namespaces. A meaningful message should be displayed to the tenant owner informing that during the maintenance window, no CREATE/UPDATE/DELETE operations are permitted.

**Comment by prometherion** [comment]
Seems an interesting feature, I'm just concerned regarding the ValidatingWebhookConfiguration required that would be a catch-all for all the underlying resources, doesn't look so confident to me.

I'm ok with the label, although since this change would require a new field in the CRD specification, we could add it effortlessly.

**Comment by prometherion** [comment]
Got a question regarding this: should we block *all* API actions from any user or just the ones from the Tenant owner?

Because I'm thinking the case when QoS, PodPriority, and Preemption kick in: if we block all the requests, an anchored Tenant could disrupt other ones or the Kubernetes critical components itself.

The idea to avoid this sort of deadlock would be to block all requests except the ones with a Service Account coming from `system:serviceaccounts:kube`.

**Comment by prometherion** [comment]
Also regarding deletion of a Tenant performed by a Cluster Administrator: should be it allowed when a Tenant is frozen?

I'd say no, an unfreeze would be required since it's the actor involved and they have to play by the rules.

**Comment by bsctl** [comment]
> I'm ok with the label, although since this change would require a new field in the CRD specification, we could add it effortlessly.

yes, label is effortless without change the tenant CRD

> Got a question regarding this: should we block all API actions from any user or just the ones from the Tenant owner?

Imho, the latter one. The intention of this feature is to block write activity from tenant owners during maintenance windows, for example, cluster or dedicated node pools upgrade. In a multitenacy scenario, likely a public CaaS, it becomes hard for the cluster admin to keep discipline among all tenant users, emailing them id not enough.

**Comment by prometherion** [comment]
> The intention of this feature is to block write activity from tenant owners during maintenance windows, for example, cluster or dedicated node pools upgrade.

We should also block operations on behalf of the underlying Service Account, not only the Tenant Owners.
