### ISSUE TITLE
Registry is forbidden for the current Tenant although it was in the allowed list

### ISSUE THREAD

**Issue by mendrugory** [clastix/capsule#452]
# Bug description

Capsule provides a mechanism to restrict the allowed registries by tenant. In the following example, the filter is not allowing an known Azure registry (ACR) because the internal filters are assuming that it is under `docker.io` registry, therefore a different one which is taken as default (internally).

# How to reproduce

We have seen this behaviour in Azure.

1. Provide a ACR (Azure container registry) under your resource group and push your image

```bash
$ az acr create -g <you resource group> -n myregistry --sku Standard --location <your location>
$ az acr login -n myregistry
$ docker tag myapp:latest myregistry.azurecr.io/myapp
$ docker push myregistry.azurecr.io/myapp
```

2. Deploy a AKS cluster and install Capsule

*Tenant definition*

```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: mytenant
spec:
  containerRegistries:
    allowed:
    - myregistry.azurecr.io
  owners:
  - kind: Group
    name: d232dc49-25e1-43f7-91f6-182979fb81b5
status:
  namespaces:
  - production
  size: 3
  state: Active
```

> Note: Tenant owner is a Azure Active Directory group.

3. Run a Pod using an image from your ACR

```bash
$ kubectl run app --image=myregistry.azurecr.io/myapp:latest -n production

Error from server (Container image myregistry.azurecr.io/myapp:latest registry is forbidden for the current Tenant: use one from the following list (myregistry.azurecr.io)): admission webhook "pods.capsule.clastix.io" denied the request: Container image myregistry.azurecr.io/myapp:latest registry is forbidden for the current Tenant: use one from the following list (myregistry.azurecr.io)
```

# Expected behavior

I would expect to have the possibility of pulling that image.

# Logs

``` bash
{"level":"debug","ts":"2021-10-18T12:05:52.281Z","logger":"controller-runtime.webhook.webhooks","msg":"received request","webhook":"/cordoning","UID":"357c3860-9f74-49d6-a740-b41c45f1cfcf","kind":"/v1, Kind=Pod","resource":{"group":"","version":"v1","resource":"pods"}}
{"level":"debug","ts":"2021-10-18T12:05:52.283Z","logger":"controller-runtime.webhook.webhooks","msg":"wrote response","webhook":"/cordoning","code":200,"reason":"","UID":"357c3860-9f74-49d6-a740-b41c45f1cfcf","allowed":true}
{"level":"debug","ts":"2021-10-18T12:05:52.328Z","logger":"controller-runtime.webhook.webhooks","msg":"received request","webhook":"/pods","UID":"e7f2dfe8-e9ef-4d1b-9d6f-baee07a4f4ec","kind":"/v1, Kind=Pod","resource":{"group":"","version":"v1","resource":"pods"}}
{"level":"debug","ts":"2021-10-18T12:05:52.328Z","logger":"controller-runtime.webhook.webhooks","msg":"wrote response","webhook":"/pods","code":403,"reason":"Container image myregistry.azurecr.io/myapp:latest registry is forbidden for the current Tenant: use one from the following list (myregistry.azurecr.io)","UID":"e7f2dfe8-e9ef-4d1b-9d6f-baee07a4f4ec","allowed":false}
{"level":"debug","ts":"2021-10-18T12:05:52.328Z","logger":"controller-runtime.manager.events","msg":"Warning","object":{"kind":"Tenant","name":"mytenant","uid":"e798aad4-e446-41d5-b724-6287460aa91b","apiVersion":"capsule.clastix.io/v1beta1","resourceVersion":"15294"},"reason":"ForbiddenContainerRegistry","message":"Pod production/app is using a forbidden registry docker.io is forbidden for the current Tenant"}
```

# Additional context

- Capsule version: `0.1.0`
- Helm Chart version: `0.1.0`
- Kubernetes version: `v1.22.2`

**Comment by prometherion** [comment]
The reason for this bug is this piece of code.

https://github.com/clastix/capsule/blob/0784dc7177da40ae5b3ef8831f72a2e1c02797a8/pkg/webhook/pod/containerregistry_registry.go#L55-L65

Essentially, we're doing regex parsing of the container image name to extract registry, repository, image, and tag elements from the FQCI.

With the Azure Container Registry example (`solarregistry.azurecr.io/nginx:latest`), this fails, because `myregistry.azurecr.io/myapp:latest` will be grouped [as follows](https://regex101.com/r/ELubtd/1), marking the registry `solarregistry.azurecr.io` as a repository, although it is incorrect.

While designing this feature, we took for granted that the fully qualified container image (FQCI) name was the one used in the said regex and that just the Docker Hub was an exception: with that if a registry was missing, we were returning [`docker.io` as the default registry](https://github.com/clastix/capsule/blob/b58ca3a7d78dabd8f7438b3ea925896f1002ed50/pkg/webhook/pod/containerregistry_registry.go#L10).

https://github.com/clastix/capsule/blob/b58ca3a7d78dabd8f7438b3ea925896f1002ed50/pkg/webhook/pod/containerregistry_registry.go#L14-L23

Now, we know there is an additional exception, and many others could occur and action must be put in place.

1. the tenant owners would be forced to use fully qualified container image names: instead of using `nginx:latest`, that would be `docker.io/library/nginx:latest`
2. adding a default registry to each Tenant, rather than using [the hard-coded one](https://github.com/clastix/capsule/blob/b58ca3a7d78dabd8f7438b3ea925896f1002ed50/pkg/webhook/pod/containerregistry_registry.go#L10), although this is not going to solve the issue with Azure Container Registry since it seems not managing images at repository level as Quay.io would do (e.g. `quay.io/clastix/capsule`).
3. performing a lookup at each Pod launch when enforcement of container registries is enabled.

Let's try finding the pros and cons for each option.

# 1. Enforcement of fully qualified container image names

### Pros

- No breaking changes in Tenant API
- Easy to solve with a patch release

### Cons

- It could break Capsule installations where container registries are enabled
- Not a clean UX: end-users are used to deploying containers without caring so much on names

# 2. Default registry at the Tenant level

### Pros

- Fine-grained control

### Cons

- Doesn't solve entirely the issue
- That would require, rather, an additional regex to parse images and this could be even more of a mess
- Change must be addressed in the Custom Resource instance annotations field

# 3. Lookup at each Pod launch

### Pros 

- The best fit for this issue

### Cons

- absolutely expensive, would require an in-memory cache to avoid polling the registries (that could then incurring in rate-limiting in some container registries)

---

With all that said, the first option seems the most reasonable to me: we must pay absolute attention when documenting this change in order to maintain reliability and business continuity for end-users using this feature of Capsule in production.

@mendrugory @bsctl @MaxFedotov feedback is welcome, as usual, as well additional solutions I hadn't thought about.
