### ISSUE TITLE
default CRUD access for own namespaces

### ISSUE THREAD

**Issue by invent360** [clastix/capsule#679]
# Bug description

Would like to understand why Tenant owners have no rights to list/delete their created namespaces by default.

# How to reproduce

1. Install Tenant using helm (on k3d)
2. Create a tenant for alice
```
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: oil
spec:
  owners:
  - name: alice
    kind: User
```
3. Create KUBECONFIG for alice using `./hack/create-user.sh alice oil`

4. login as alice `export KUBECONFIG=alice-oil.kubeconfig`

5. create namespaces in alice's tenant `kubectl create namespace oil-production` and `kubectl create namespace oil-development`
6. List namespaces in alice's oil tenant `kubectl get ns`
# Expected behavior
The following namespaces created by alice  (in the oil tenant) should be listed 
```
oil-production
oil-development
```

# Logs
`Error from server (Forbidden): namespaces is forbidden: User "alice" cannot list resource "namespaces" in API group "" at the cluster scope`

# Additional context

- Capsule version: (`v0.1.3`)
- Helm Chart version: (`capsule-0.1.12`)
- Kubernetes version: 
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4+k3s1", GitCommit:"c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e", GitTreeState:"clean", BuildDate:"2022-08-25T03:46:35Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/arm64"}
```

**Comment by prometherion** [comment]
This is not properly a bug, rather, facing the limitations of Kubernetes itself with the multi-tenancy topic.

The Kubernetes API Server has been designed around RBAC, rather than ACL, which means that users are granted around resources (listing, or not, all the Namespace objects) rather than filtering (listing all owned Namespace objects).

Unfortunately, this is something that cannot be fixed by using the bare Kubernetes API Server, however, at CLASTIX Labs we developed the [capsule-proxy](https://github.com/clastix/capsule-proxy), a simple reverse proxy that allows listing cluster-scoped resources such as Ingress Class, Storage Class, Pod Priority Class, and Namespace objects owned by a Tenant.

It's used in production by several people, mostly notable @MaxFedotov, @GlassOfWhiskey, and IIRC @oliverbaehler.

In the official Capsule documentation, we tried to explain the problem of listing Namespaces, and how we solved that with the proxy, at the following [link](https://capsule.clastix.io/docs/general/proxy).

For code maintainability, we decided to open a new repository for the proxy code-base, and if you don't mind I'd like to close this issue with your approval and ask you to open any issue, feature request, or question to the [proxy repository](https://github.com/clastix/capsule-proxy).

Waiting for your feedback, and thanks for giving it a try to Capsule! 🤗

**Comment by invent360** [comment]
@prometherion thanks so much for the prompt response and for pointing me to the right direction. Was playing around with hierarchical-namespaces, really didn't like the flat nature of parent/child namespace and came around the clastix solution which is more elegant. Kudos for the great work and please feel free to close this issue.
