### ISSUE TITLE
Capsule always assumes first found tenant as an owner for namespace

### ISSUE THREAD

**Issue by MaxFedotov** [clastix/capsule#76]
Current implementation of owner_refrence webhook use following logic to set tenant for a namespace
https://github.com/clastix/capsule/blob/a99153cbe70432d7e21ad5a2610ba737b1ba27d3/pkg/webhook/owner_reference/patching.go#L84-L93
So basically we find all Tenants for a user\group who created a namespace, and select first one from it (and I think that this logic should be rewritten if future because it's a bit strange for me - a good option will be to set `force-tenant-prefix` by default, so all this magic will gone)

**Comment by bsctl** [comment]
@MaxFedotov thanks for pointing on this.

The `--force-tenant-prefix` option has been introduced because of a customer requirement. However, this should not be the forced as default behaviour because forcing a naming convention, e.g. `tenant-namespace` sounds too much restrictive, so we decided to keep it as optional.

Generally speaking, we need to use a lookup algorithm to find the belonging tenant after a user/group/sa who created a namespace. Of course, if the `--force-tenant-prefix=true` the lookup can be simplified because you already have the tenant name in the name of namespace but this cannot be assumed as the sole option.

@prometherion could you please laborate more the reasons why we implemented the lookup above in that way? Should a user/group/sa own more than one tenant at time?

**Comment by prometherion** [comment]
What we could assume here is to change the default behavior, let's write down some specs.

### A Tenant Owner owns just a single Tenant

All namespaces will be assigned to the single available Tenant, end of the story 👍🏻 

### A Tenant Owner owns two or more Tenant

Actually, we're assigning the Namespace to the first Tenant available, and this behavior seems odd.
What we could do here is to perform validation: intercepting the Namespace creation request, we check if we have two or more Tenant and, in this case, rejecting the request since the Tenant Owner has to specify which Tenant they have to use using the available labels.

### A Tenant Owner handled by a Group (or ServiceAccount) creates a Namespace

We have to follow the pattern `${tenant_name}-${desired_name}`, otherwise we cannot retrieve the right ownership except by a high computational cost.

---

@bsctl @MaxFedotov any thoughts?

**Comment by MaxFedotov** [comment]
I don't know if it is a good idea to have different logic in case of user or group\sa tenant owner as it's a bit confusing from the end-user perspective. 

> A Tenant Owner handled by a Group (or ServiceAccount) creates a Namespace
As I understand, it's impossible to find out if a Tenant Owner is a User or Group, as it can be both, e.g. my username is m_fedotov@wargaming.net and I am a member of a group WGAdmins. I can have my own tenant, as a user. And my group can also have it's own tenant too.

So from my POV we should do the following things:
- Create a webhook, which will validate that `${tenant_name}` can have only alphanumeric characters
- If we had `${tenant_name}` label when creating NS -> assign it to the specified tenant
- if we had `--enforce-tenant-prefix` -> find tenant name by splitting `${namespace_name}`
- build `&capsulev1alpha1.TenantList{}` for `req.UserInfo.Username` and `req.UserInfo.Groups`. If there is only a single tenant -> assign namespace to it. In other cases return an error like `Unable to find a tenant for the namespace. Either use --enforce-tenant-prefix or add label specifying tenant name`

**Comment by prometherion** [comment]
What is concerning to me is the case when a User belongs to several Groups, meaning to iterate all over of these and we cannot assume to pick the first available occurrence, since the User could be assigned to several Groups that got several Tenant resources assigned.

The ServiceAccount case is pretty straightforward since I guess we're able to determinate that from the Admission Request as we would do with User ones, so we have to find a viable solution for the Group scenario.

**Comment by MaxFedotov** [comment]
> The ServiceAccount case is pretty straightforward since I guess we're able to determinate that from the Admission Request as we would do with User ones, so we have to find a viable solution for the Group scenario.

I don't think so, as UserInfo struct looks like 
```
type UserInfo struct {
	// The name that uniquely identifies this user among all active users.
	// +optional
	Username string `json:"username,omitempty" protobuf:"bytes,1,opt,name=username"`
	// A unique value that identifies this user across time. If this user is
	// deleted and another user by the same name is added, they will have
	// different UIDs.
	// +optional
	UID string `json:"uid,omitempty" protobuf:"bytes,2,opt,name=uid"`
	// The names of groups this user is a part of.
	// +optional
	Groups []string `json:"groups,omitempty" protobuf:"bytes,3,rep,name=groups"`
	// Any additional information provided by the authenticator.
	// +optional
	Extra map[string]ExtraValue `json:"extra,omitempty" protobuf:"bytes,4,rep,name=extra"`
}
```
and it's impossible to say if it User or SA

**Comment by MaxFedotov** [comment]
And I think that SA couldn't be a tenant owner, as it is namespace scoped

**Comment by prometherion** [comment]
Nice catch, you're right.

Let's abandon the idea of SA as Owner and focus just on a viable solution for Groups.

**Comment by MaxFedotov** [comment]
@prometherion 
what if we use this logic
```
func (h *handler) listTenantsForOwnerKind(ctx context.Context, ownerKind string, ownerName string, clt client.Client) (*v1alpha1.TenantList, error) {
	tl := &v1alpha1.TenantList{}
	f := clt.MatchingFields{
		".spec.owner.ownerkind": fmt.Sprintf("%s:%s", ownerKind, ownerName),
	}
	err := clt.List(ctx, tl, f)
	return tl, err
}

func (h *handler) OnCreate(clt client.Client, decoder *admission.Decoder) capsulewebhook.Func {
	return func(ctx context.Context, req admission.Request) admission.Response {
		ns := &corev1.Namespace{}
		if err := decoder.Decode(req, ns); err != nil {
			return admission.Errored(http.StatusBadRequest, err)
		}
		ln, err := capsulev1alpha1.GetTypeLabel(&capsulev1alpha1.Tenant{})
		if err != nil {
			return admission.Errored(http.StatusBadRequest, err)
		}
		// If we already had TenantName label on NS -> assign to it
		if len(ns.ObjectMeta.Labels) > 0 {
			l, ok := ns.ObjectMeta.Labels[ln]
			// assigning namespace to Tenant in case of label
			if ok {
				// retrieving the selected Tenant
				t := &capsulev1alpha1.Tenant{}
				if err := clt.Get(ctx, types.NamespacedName{Name: l}, t); err != nil {
					return admission.Errored(http.StatusBadRequest, err)
				}
				// Tenant owner must adhere to user that asked for NS creation
				if t.Spec.Owner != req.UserInfo.Username {
					return admission.Denied("Cannot assign the desired namespace to a non-owned Tenant")
				}
				// Patching the response
				return h.patchResponseForOwnerRef(t, ns)
			}

		}
		// If we forceTenantPrefix -> find Tenant from NS name
		if forceTenantPrefix {
			t := &v1alpha1.Tenant{}
			tenantName := strings.Split(namespaceName, "-")[0]
			if err := client.Get(ctx, types.NamespacedName{Name: tenantName}, t); err != nil {
				return admission.Errored(http.StatusBadRequest, err)
			}
			return h.patchResponseForOwnerRef(t, ns)
		}

		tenants := []*capsulev1alpha1.Tenant{}

		// Find tenants belonging to user
		tlu, err := h.listTenantsForOwnerKind(ctx, "User", req.UserInfo.Username, clt)
		if err != nil {
			return admission.Errored(http.StatusBadRequest, err)
		}
		// No groups single tenant short-circuit
		if len(req.UserInfo.Groups) == 0 && len(tlu.Items) == 1 {
				return h.patchResponseForOwnerRef(tlu.Items[0], ns)
		}

		switch userTenants := len(tlu.Items); {
		case userTenants > 1:
			return admission.Denied("Unable to assign namespace to tenant. Please use " + ln + " label when creating a namespace")
		case userTenants == 1:
			tenants = append(tenants, tlu.Items[0])
		}

		for _, group := range userInfo.Groups {
			tl, err := h.listTenantsForOwnerKind(ctx, "Group", req.UserInfo.Groups, clt)
			if err != nil {
				return admission.Errored(http.StatusBadRequest, err)
			}
			tenants = append(tenants, tl.Items...)
			// more than one tenant found, returning error
			if len(tenants) > 1 {
				return admission.Denied("Unable to assign namespace to tenant. Please use " + ln + " label when creating a namespace")
			}
		}
		
		// Single tenant found for group
		if len(tenants) == 1 {
			return h.patchResponseForOwnerRef(tenants[0], ns)
		}

		return admission.Denied("You do not have any Tenant assigned: please, reach out the system administrators")
	}
}
```

**Comment by bsctl** [comment]
@prometherion @MaxFedotov for my understanding here, we have some cases already addressed, eg. a User owns one or more Tenants. But other cases already not addressed, eg. a User is part of a Group and the its Group owns one or more Tenants.

For my understanding, the latter case is the most tricky as different combinations are possible. But these cases can be simplified if we assume alway `--enforce-tenant-prefix=true`.

As we would to move forward with Capsule adoption, I would suggest to set `--enforce-tenant-prefix=true` as default, so that #71 is unlocked.

We'll open a new issue to address the cases when the `--enforce-tenant-prefix=false` and leave for later the discussion about a better implementation strategy. Sounds good?

And yes, it does not make sense to have a SA as Tenant Owner. My bad.

**Comment by prometherion** [comment]
> we still need a webhook to enforce tenant name to be alphanumeric

We can use a regex validation at CRDs level, rather: should be easy to achieve.

**Comment by MaxFedotov** [comment]
@prometherion 
It was my first intention, but as we are using 
```
type Tenant struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   TenantSpec   `json:"spec,omitempty"`
	Status TenantStatus `json:"status,omitempty"`
}
```

and metav1.ObjectMeta is imported from `metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"` you can't add kubebuilder comments with regexp validation for it (or you had to vendor and patch it)

**Comment by prometherion** [comment]
Gosh, you're totally right 🤦🏻‍♂️ 

Let's see if we can find a workaround, otherwise we have to switch over a validating webhook for the Tenant resources.

**Comment by MaxFedotov** [comment]
#71 implements validating webhook and logic from https://github.com/clastix/capsule/issues/76#issuecomment-688826105

**Comment by prometherion** [comment]
> #71 implements validating webhook and logic from [#76 (comment)](https://github.com/clastix/capsule/issues/76#issuecomment-688826105)

So we can say this has been accomplished as expected, no more auto-selection of first Tenant in case of multiple ones?
