### ISSUE TITLE
Users should not be able to create tenant when Capsule is uninstalled 

### ISSUE THREAD

**Issue by meetdpv** [clastix/capsule#788]
# Bug description

After uninstallation Capsule helm chart, we are still able to create tenants in the cluster.

# How to reproduce

1. Uninstall Capsule helm chart - helm uninstall capsule -n capsule-system
2. Verify that helm chart is uninstalled
3. Verify that no pods are running in Capsule-system namespace
4. Create a new tenant with yaml
5. User is able to create the namespace

# Expected behavior

Since Capsule is uninstalled, users should not be able to create tenants in the cluster. The purpose of uninstalling Capsule is to stop user from using Capsule (tenant creation etc.).

It works as expected when you capsule pod has any issues (scale down to zero or having some port conflict or not in running state etc.), it shows error "Error no endpoints available for service "capsule-webhook-service"
We need the similar error when Capsule is uninstalled.

Screenshots attached.

# Logs

Not Applicable as pod is deleted

# Additional context

- Capsule version: 0.3.3
- Helm Chart version: capsule-0.4.5
- Kubernetes version: v1.23
[Screenshots.docx](https://github.com/clastix/capsule/files/12088866/Screenshots.docx)

**Comment by prometherion** [comment]
I'm a bit confused here, you're referring to Namespace and Tenant.

The issue you're facing is as cluster administrator in creating Tenants or tenant owners in creating Namespaces?

**Comment by meetdpv** [comment]
When you do not want to the users to create tenants on a cluster, you uninstall Capsule from the cluster. You can still create the tenant on the cluster even though Capsule is uninstalled. This should not be allowed. This may be due to the CRD left behind after Capsule uninstall. 
Please refer to the screenshots.

**Comment by prometherion** [comment]
There are no screenshots attached to the issue, firstly.

Second, this is not a bug report since sticking to the Helm philosophy dealing with CRDs installed with it.

By design, Helm doesn't uninstall CRDs since their deletions would cause the full wipe of it from Kubernetes, as well as other depending resources, the depending Namespaces with their content, like Persistent Volume, thus data.

For users are well known aware of Kubernetes internals and how CRDs work, this is not an issue, and gives enough freedom to them in continue in their preferred clean-up strategy, such as removing all the OwnerReference from all the Namespaces and finally delete the Cards or, rather, install Capsule back and having everything set back.
